<#
.SYNOPSIS
    Starts the central platform stack (IP-04).

.DESCRIPTION
    One command to bring up the Angular dashboard, the ASP.NET Core Backend, SQL Server, and the
    EF Core migration job. Creates a .env with generated local-development secrets on first run,
    then builds and starts the stack and waits for it to become healthy.

    Only Docker Desktop is required. No local Node.js, Angular CLI, .NET SDK, SQL Server, or EF
    Core tooling is needed.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File deployment/start.ps1
#>

[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Resolve the repository root from the script's own location, so the script works from any current
# working directory.
$repositoryRoot = Split-Path -Parent $PSScriptRoot
Push-Location $repositoryRoot

try {
    Write-Host ''
    Write-Host 'Weapon Detection - central platform' -ForegroundColor Cyan
    Write-Host '===================================' -ForegroundColor Cyan
    Write-Host ''

    # --- 1. Preconditions --------------------------------------------------------------------
    Write-Host 'Checking Docker...' -NoNewline

    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        Write-Host ' failed' -ForegroundColor Red
        throw 'Docker is not installed, or `docker` is not on PATH. Install Docker Desktop: https://www.docker.com/products/docker-desktop/'
    }

    # `docker info` fails when the CLI is present but the daemon is not running — the usual case
    # when Docker Desktop has not been started yet.
    docker info --format '{{.ServerVersion}}' *> $null
    if ($LASTEXITCODE -ne 0) {
        Write-Host ' failed' -ForegroundColor Red
        throw 'Docker Desktop is installed but the daemon is not running. Start Docker Desktop, wait until it reports "Engine running", then run this script again.'
    }

    docker compose version *> $null
    if ($LASTEXITCODE -ne 0) {
        Write-Host ' failed' -ForegroundColor Red
        throw 'Docker Compose v2 is unavailable. Update Docker Desktop to a version that ships `docker compose`.'
    }

    Write-Host ' ok' -ForegroundColor Green

    # --- 2. Configuration --------------------------------------------------------------------
    $envPath = Join-Path $repositoryRoot '.env'

    if (Test-Path $envPath) {
        # Never overwrite: the existing file may hold credentials tied to the data already in the
        # SQL Server volume, and replacing them would lock the stack out of its own database.
        Write-Host 'Using the existing .env (left unchanged).' -ForegroundColor Green
    }
    else {
        Write-Host 'No .env found - creating one with generated local-development secrets...'

        # Character set chosen so a generated value can never corrupt the files and strings it
        # passes through: no '$' or '{' '}' (Compose interpolation), no ';' or '=' (connection
        # string delimiters), no '#' (.env comment), no quotes, backslash, or backtick.
        $alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.+*!?'

        function New-Secret {
            param([int] $Length)

            $bytes = New-Object byte[] $Length

            # Cryptographically secure, unlike Get-Random. RNGCryptoServiceProvider is used rather
            # than RandomNumberGenerator.Fill because the latter does not exist on the .NET
            # Framework that Windows PowerShell 5.1 runs on, and this script must work there.
            $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
            try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }

            $characters = foreach ($byte in $bytes) { $alphabet[$byte % $alphabet.Length] }
            -join $characters
        }

        function New-CompliantPassword {
            param([int] $Length)

            # SQL Server requires at least three of: uppercase, lowercase, digit, non-alphanumeric.
            # Generate until all four are present rather than splicing characters in at fixed
            # positions, which would leak structure.
            while ($true) {
                $candidate = New-Secret -Length $Length
                if ($candidate -cmatch '[A-Z]' -and
                    $candidate -cmatch '[a-z]' -and
                    $candidate -match '[0-9]' -and
                    $candidate -match '[-_.+*!?]') {
                    return $candidate
                }
            }
        }

        $sqlPassword   = New-CompliantPassword -Length 32
        $adminPassword = New-CompliantPassword -Length 24
        # Comfortably above the 32-UTF-8-byte minimum JwtOptionsValidator enforces.
        $jwtSigningKey = New-Secret -Length 64

        $contents = @"
# Generated by deployment/start.ps1 for local development.
# This file is git-ignored and must never be committed.
# Delete it and re-run start.ps1 to regenerate (see deployment/README.md - doing so requires
# resetting the database volume, because the SQL password would no longer match).

APP_PORT=8080
SQL_DATABASE=WeaponDetection
SQL_SERVER_PASSWORD=$sqlPassword
JWT_SIGNING_KEY=$jwtSigningKey
ADMIN_IDENTIFIER=admin
ADMIN_PASSWORD=$adminPassword
"@

        # UTF8 without BOM: a BOM would become part of the first variable name.
        [System.IO.File]::WriteAllText($envPath, $contents, [System.Text.UTF8Encoding]::new($false))

        # Secret values are never echoed. The Admin password is readable from the .env file when
        # the user needs it to sign in.
        Write-Host 'Created .env with generated secrets.' -ForegroundColor Green
        Write-Host '  Sign-in credentials are in the .env file (ADMIN_IDENTIFIER / ADMIN_PASSWORD).'
        Write-Host '  Values are not printed here on purpose.'
    }

    # Read APP_PORT back for the URLs shown at the end. Only this non-secret value is parsed.
    $appPort = '8080'
    foreach ($line in Get-Content $envPath) {
        if ($line -match '^\s*APP_PORT\s*=\s*(.+?)\s*$') { $appPort = $Matches[1] }
    }

    # --- 3. Build and start ------------------------------------------------------------------
    Write-Host ''
    Write-Host 'Building and starting the stack (first run downloads images and can take several minutes)...'
    Write-Host ''

    docker compose up --build -d
    if ($LASTEXITCODE -ne 0) {
        throw 'docker compose up failed. Inspect the output above, or run: powershell -ExecutionPolicy Bypass -File deployment/logs.ps1'
    }

    # --- 4. Wait for health ------------------------------------------------------------------
    Write-Host ''
    Write-Host 'Waiting for services to become healthy...' -NoNewline

    $timeout  = [TimeSpan]::FromMinutes(5)
    $deadline = (Get-Date).Add($timeout)
    $healthy  = $false

    while ((Get-Date) -lt $deadline) {
        $rows = docker compose ps --format json 2>$null

        if ($LASTEXITCODE -eq 0 -and $rows) {
            # Compose emits either one JSON object per line or a single JSON array, depending on
            # version; normalise both into a list.
            $services = @(
                $rows | Where-Object { $_ } | ForEach-Object { $_ | ConvertFrom-Json }
            )

            $frontend = $services | Where-Object { $_.Service -eq 'frontend' } | Select-Object -First 1
            $backend  = $services | Where-Object { $_.Service -eq 'backend' }  | Select-Object -First 1

            if ($frontend -and $backend -and
                $frontend.Health -eq 'healthy' -and $backend.Health -eq 'healthy') {
                $healthy = $true
                break
            }
        }

        Write-Host '.' -NoNewline
        Start-Sleep -Seconds 3
    }

    Write-Host ''
    Write-Host ''

    docker compose ps

    if (-not $healthy) {
        Write-Host ''
        Write-Host "The stack did not become healthy within $($timeout.TotalMinutes) minutes." -ForegroundColor Red
        Write-Host 'Inspect the logs with:' -ForegroundColor Yellow
        Write-Host '  powershell -ExecutionPolicy Bypass -File deployment/logs.ps1'
        Write-Host 'See deployment/README.md for troubleshooting.'
        exit 1
    }

    # --- 5. Report ---------------------------------------------------------------------------
    Write-Host ''
    Write-Host 'The central platform is running.' -ForegroundColor Green
    Write-Host ''
    Write-Host "  Central platform: http://localhost:$appPort"
    Write-Host "  Backend health:   http://localhost:$appPort/api/v1/health"
    Write-Host ''
    Write-Host '  Logs:  powershell -ExecutionPolicy Bypass -File deployment/logs.ps1'
    Write-Host '  Stop:  powershell -ExecutionPolicy Bypass -File deployment/stop.ps1'
    Write-Host ''
}
finally {
    Pop-Location
}
