// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeaponDetection.Infrastructure.Persistence;

#nullable disable

namespace WeaponDetection.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WeaponDetectionDbContext))]
    partial class WeaponDetectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeaponDetection.Domain.ActivationKey", b =>
                {
                    b.Property<string>("ActivationKeyId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("DeviceRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ActivationKeyId");

                    b.HasIndex("DeviceRecordId")
                        .IsUnique()
                        .HasDatabaseName("IX_ActivationKeys_DeviceRecordId_Unconsumed")
                        .HasFilter("[Status] = 'Unconsumed'");

                    b.HasIndex("DeviceRecordId", "Status");

                    b.ToTable("ActivationKeys", (string)null);
                });

            modelBuilder.Entity("WeaponDetection.Domain.AdminSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("AdminSessions", (string)null);
                });

            modelBuilder.Entity("WeaponDetection.Domain.AdminUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CredentialIdentifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("UserId");

                    b.HasIndex("CredentialIdentifier")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("WeaponDetection.Domain.Alert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BboxHeight")
                        .HasColumnType("float");

                    b.Property<double>("BboxLeft")
                        .HasColumnType("float");

                    b.Property<double>("BboxTop")
                        .HasColumnType("float");

                    b.Property<double>("BboxWidth")
                        .HasColumnType("float");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FrameHeight")
                        .HasColumnType("int");

                    b.Property<long>("FrameNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("FrameWidth")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SnapshotContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("SnapshotReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SnapshotReference")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("SnapshotSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("SnapshotSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("AlertId");

                    b.HasIndex("CameraId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("IX_Alerts_DeviceId_EventId");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("WeaponDetection.Domain.Branch", b =>
                {
                    b.Property<Guid>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("WeaponDetection.Domain.BranchDailyAlertQuota", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocalDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("AcceptedAlertCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstSuppressedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GunSuppressedCount")
                        .HasColumnType("int");

                    b.Property<int>("KnifeSuppressedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSuppressedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SuppressedDetectionCount")
                        .HasColumnType("int");

                    b.HasKey("BranchId", "LocalDate")
                        .HasName("PK_BranchDailyAlertQuotas");

                    b.ToTable("BranchDailyAlertQuotas", (string)null);
                });

            modelBuilder.Entity("WeaponDetection.Domain.Camera", b =>
                {
                    b.Property<Guid>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CameraKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RtspUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("SourceOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CameraId");

                    b.HasIndex("BranchId");

                    b.HasIndex("BranchId", "CameraKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Cameras_BranchId_CameraKey");

                    b.HasIndex("BranchId", "SourceOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_Cameras_BranchId_SourceOrder_Enabled")
                        .HasFilter("[Enabled] = 1");

                    b.ToTable("Cameras", (string)null);
                });

            modelBuilder.Entity("WeaponDetection.Domain.Device", b =>
                {
                    b.Property<Guid>("DeviceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AnnotatedOutputBaseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JetsonHost")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastKnownAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProtectedSharedSecret")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("RtspOutputPort")
                        .HasColumnType("int");

                    b.HasKey("DeviceRecordId");

                    b.HasIndex("BranchId")
                        .IsUnique();

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasFilter("[DeviceId] IS NOT NULL");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("WeaponDetection.Domain.SuppressedDetectionEvent", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocalDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DeviceId", "EventId")
                        .HasName("PK_SuppressedDetectionEvents");

                    b.HasIndex("BranchId", "LocalDate");

                    b.ToTable("SuppressedDetectionEvents", (string)null);
                });

            modelBuilder.Entity("WeaponDetection.Domain.ActivationKey", b =>
                {
                    b.HasOne("WeaponDetection.Domain.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeaponDetection.Domain.AdminSession", b =>
                {
                    b.HasOne("WeaponDetection.Domain.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeaponDetection.Domain.Camera", b =>
                {
                    b.HasOne("WeaponDetection.Domain.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeaponDetection.Domain.Device", b =>
                {
                    b.HasOne("WeaponDetection.Domain.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
